== Data Validation


=== Zależności

[source,xml]
----
<dependency>
<groupId>org.hibernate</groupId>
<artifactId>hibernate-validator</artifactId>
<version>5.1.0.Alpha1</version>
</dependency>
<!-- these are only necessary if not in a Java EE environment -->
<dependency>
<groupId>org.hibernate</groupId>
<artifactId>hibernate-validator-cdi</artifactId>
<version>5.1.0.Alpha1</version>
</dependency>
<dependency>
<groupId>javax.el</groupId>
<artifactId>javax.el-api</artifactId>
<version>2.2.4</version>
</dependency>

<dependency>
<groupId>org.glassfish.web</groupId>
<artifactId>javax.el</artifactId>
<version>2.2.4</version>
</dependency>
----




=== Validation-mode

 ** domyślnie włączony

        AUTO: if Bean Validation is present in the classpath, CALLBACK and DDL are activated.

        CALLBACK: entities are validated on creation, update and deletion. If no Bean Validation provider is present, an exception is raised at initialization time.

        DDL: (not standard, see below) database schemas are entities are validated on creation, update and deletion. If no Bean Validation provider is present, an exception is raised at initialization time.

        NONE: Bean Validation is not used at all

    Unfortunately, DDL is not standard mode (though extremely useful) and you will not be able to put it in <validation-mode>. To use it, add a regular property

** Przykład konfiguracji w persistence.xml

[source,xml]
----
    <property name="javax.persistence.validation.mode">
      ddl
    </property>
----
  
== Własny walidator

=== Adnotacje

== @DecimalMax 

** Numeric

== @DecimalMin  

**   Numeric      

== @Min    

** Numeric   

== @Max

**  Numeric    

== @Null   

** obiekt musi być null



== @NotNull 

** obiekt nie może być null'em


== @Digits  

** Numeric

== @Past  

** data musi być w przeszłości

== @Future   

** data musi być w przyszłości

== @AssertFalse  

** boolean musi być false


== @Size   

** String||Collection||Map||Arrray  długość/rozmiar

== @AssertTrue   

** boolean musi być true

== @Pattern  

** tworzymy własny pattern 

