= JPA/Hibernate camp
:docInfo1
:numbered:
:icons: font
:pagenums:
:imagesdir: img
:iconsdir: ./icons
:stylesdir: ./styles
:scriptsdir: ./js

:image-link: https://pbs.twimg.com/profile_images/425289501980639233/tUWf7KiC.jpeg
ifndef::sourcedir[:sourcedir: ./src/main/java/]
ifndef::resourcedir[:resourcedir: ./src/main/resources/]
ifndef::imgsdir[:imgsdir: ./../img]
:source-highlighter: coderay


== O mnie
* Architect Solution - RiscoSoftware 
* JavaTech trener : Spring ekosystem, JPA , EIP Camel 
* Sages trener : JPA , EIP - Apache Camel 
* blog link:http://przewidywalna-java.blogspot.com[]
* twitter przodownikR1

image:{image-link} [role='img-circle']

== Źródła wiedzy 
 - Hibernate in Action
 - Java Persistence with Hibernate
 - Java JEE 6
 - Pro JPA 2
 - Pro JPA 2: Mastering the Java(TM) Persistence API (Expert's Voice in Java Technology)
 - Hibernate from Novice to Professional 
 - Spring Data Modern Data Access for Enterprise Java
 - Spring Data
 - Spring Boot
 - Spring Essentials
 - Spring in Action
 - etc 

== Hibernate / JPA

== Walidacja

=== Zależności

[source,xml]
----
<dependency>
<groupId>org.hibernate</groupId>
<artifactId>hibernate-validator</artifactId>
<version>5.1.0.Alpha1</version>
</dependency>
<!-- these are only necessary if not in a Java EE environment -->
<dependency>
<groupId>org.hibernate</groupId>
<artifactId>hibernate-validator-cdi</artifactId>
<version>5.1.0.Alpha1</version>
</dependency>
<dependency>
<groupId>javax.el</groupId>
<artifactId>javax.el-api</artifactId>
<version>2.2.4</version>
</dependency>

<dependency>
<groupId>org.glassfish.web</groupId>
<artifactId>javax.el</artifactId>
<version>2.2.4</version>
</dependency>
----




=== Validation-mode

 ** domyślnie włączony

    
** Przykład konfiguracji w persistence.xml

[source,xml]
----
    <property name="javax.persistence.validation.mode">
      ddl
    </property>
----
  

=== Adnotacje

==== @DecimalMax 

** Numeric

==== @DecimalMin  

**   Numeric      

==== @Min    

** Numeric   

==== @Max

**  Numeric    

==== @Null   

** obiekt musi być null



==== @NotNull 

** obiekt nie może być null'em


==== @Digits  

** Numeric

==== @Past  

** data musi być w przeszłości

==== @Future   

** data musi być w przyszłości

==== @AssertFalse  

** boolean musi być false


==== @Size   

** String||Collection||Map||Arrray  długość/rozmiar

==== @AssertTrue   

** boolean musi być true

==== @Pattern  

** tworzymy własny pattern 


=== Własny walidator


** Przykład 

[source,java]
----
@PasswordsEqualConstraint(field = "confirmPassword")
@NoArgsConstructor
public abstract class BaseUser extends EntityCommonVersioning {

    @Transient
    @XmlTransient
    @JsonIgnore
    private String confirmPassword;

    @Transient
    @XmlTransient
    @JsonIgnore
    private String password;
    }
    
    
----

[source,java]
----
@Target({ ElementType.FIELD, ElementType.TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Size(min = 6)
@NotEmpty
@Constraint(validatedBy = PasswordsEqualConstraintValidator.class)
public @interface PasswordsEqualConstraint {
    String message() default "Wrong password";

    String field();

    Class<?>[] groups() default {};

    Class<? extends Payload>[] payload() default {};
}
----


[source,java]
----
public class PasswordsEqualConstraintValidator implements ConstraintValidator<PasswordsEqualConstraint, BaseUser> {

    @Override
    public void initialize(PasswordsEqualConstraint constraintAnnotation) {

    }

    @Override
    public boolean isValid(BaseUser user, ConstraintValidatorContext context) {
        if (!user.getPassword().equals(user.getConfirmPassword())) {
            return false;
        }
        return true;
    }

}
----

